### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by sree9578** [LibreDWG/libredwg#403]
Hi @rurban

after installing how do i configure this package for python on windows?
i built the package ...but how can i use it as python package ..how to import libredwg as said in examples..

```
"C:\Python310\DLLs\LibreDWG.py", line 15, in <module>
    import _LibreDWG
ModuleNotFoundError: No module named '_LibreDWG'

```
```
Traceback (most recent call last):
  File "LibreDWG.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/cs/Desktop/check/_LibreDWG.so: undefined symbol: dwg_getall_VX_CONTROL
```

i am getting this when i try for python 2.7 in Linux

Thanks

**Comment by rurban** [comment]
Cannot help there. swig and the python m4 setup are from external projects. python 2.7 is unsupported

**Comment by DragonCat4012** [comment]
same issue with python 3
